---
trust-domain: mobile
treeherder:
    group-names: {}

task-priority: highest

taskgraph:
    register: focusios_taskgraph:register
    repositories:
        mobile:
            name: "Focus for iOS"
    cached-task-prefix: mobile.v2.focus-ios

workers:
    aliases:
        # b-linux to be changed to bitrise
        b-linux:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            # Same in this line, b-linux to be changed to bitrise
            worker-type: 'b-linux'
        images:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'images'
        misc:
            provisioner: 'mobile-{level}'
            implementation: docker-worker
            os: linux
            worker-type: 'b-linux'

scriptworker:
    scope-prefix: mobile:focus-ios:releng
